name: Multi-Platform Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            platform: win
            artifact: '*.exe'
          - os: macos-latest
            platform: mac
            artifact: '*.dmg'
          - os: ubuntu-latest
            platform: linux
            artifact: '*.AppImage'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --${{ matrix.platform }} --config --publish always

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/${{ matrix.artifact }}
            dist/*.yml
            dist/*.blockmap
