name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送以 v 开头的标签时触发

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build and publish to GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Starting electron-builder..."
          echo "Current directory contents:"
          dir
          echo "Checking for electron-builder.yml:"
          if (Test-Path "electron-builder.yml") {
            echo "✅ electron-builder.yml found"
            Get-Content "electron-builder.yml" | Select-Object -First 10
          } else {
            echo "❌ electron-builder.yml not found"
          }
          echo "Running electron-builder..."
          npx electron-builder --win --config electron-builder.yml --publish always

      - name: Upload artifacts on success
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: release-artifacts
          path: |
            dist/*.exe
            dist/*.yml
            dist/*.blockmap

      - name: Upload debug artifacts on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: debug-artifacts
          path: |
            dist/
            out/
            *.log
            electron-builder.yml
